/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.AirlineDirectory;
import Business.CustomerDirectory;
import Business.FlightDirectory;
import UserInterface.Customers.ManageCustomerPanel;
import UserInterface.Flights.ManageAirlinesPanel;
import UserInterface.Flights.bookFlightPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Krina Thakkar
 */
public class ManageTravelAgencyPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageTravelAgencyPanel
     */
    private FlightDirectory flightDir;
    private AirlineDirectory airlineDir;
    private CustomerDirectory custdir;
    private JPanel leftpanel;
    ManageTravelAgencyPanel(JPanel leftpanel, CustomerDirectory customerdir, AirlineDirectory airlineDir) {
        initComponents();
        this.leftpanel = leftpanel;
        this.custdir = customerdir;
        this.airlineDir = airlineDir;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageCustBtn = new javax.swing.JButton();
        manageAirlinesBtn = new javax.swing.JButton();
        bookFlightBtn = new javax.swing.JButton();

        manageCustBtn.setText("Manage Customer");
        manageCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustBtnActionPerformed(evt);
            }
        });

        manageAirlinesBtn.setText("Manage Airlines");
        manageAirlinesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirlinesBtnActionPerformed(evt);
            }
        });

        bookFlightBtn.setText("Book Flight");
        bookFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(manageCustBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageAirlinesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageCustBtn)
                    .addComponent(manageAirlinesBtn)
                    .addComponent(bookFlightBtn))
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustBtnActionPerformed
        // TODO add your handling code here:
        ManageCustomerPanel panel = new ManageCustomerPanel(leftpanel,custdir);
        leftpanel.add("ManageCustomerPanel",panel);
        CardLayout layout = (CardLayout) leftpanel.getLayout();
        layout.next(leftpanel);
        
    }//GEN-LAST:event_manageCustBtnActionPerformed

    private void manageAirlinesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirlinesBtnActionPerformed
        // TODO add your handling code here:
        ManageAirlinesPanel panel = new ManageAirlinesPanel(leftpanel,airlineDir);
        leftpanel.add("ManageAirlines",panel);
        CardLayout layout = (CardLayout) leftpanel.getLayout();
        layout.next(leftpanel);
    }//GEN-LAST:event_manageAirlinesBtnActionPerformed

    private void bookFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightBtnActionPerformed
        // TODO add your handling code here:
        bookFlightPanel panel = new bookFlightPanel(leftpanel,airlineDir,custdir);
        leftpanel.add("bookFlightPanel",panel);
        CardLayout layout = (CardLayout) leftpanel.getLayout();
        layout.next(leftpanel);
    }//GEN-LAST:event_bookFlightBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookFlightBtn;
    private javax.swing.JButton manageAirlinesBtn;
    private javax.swing.JButton manageCustBtn;
    // End of variables declaration//GEN-END:variables
}
