/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Flights;

import Business.AirlineDirectory;
import Business.Airlines;
import Business.FlightDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krina Thakkar
 */
public class ManageAirlinesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirlines
     */
    private FlightDirectory flightDir;
    private AirlineDirectory airlineDir;
    private JPanel leftpanel;
    public ManageAirlinesPanel(JPanel leftpanel,AirlineDirectory airlineDir) {
        initComponents();
        this.leftpanel = leftpanel;
        this.airlineDir = airlineDir;
        this.flightDir=airlineDir.getFlightdirectory();
        populate();
    }
    
    private void populate(){
        DefaultTableModel dtm = (DefaultTableModel)tblAirlineDirectory.getModel();
        dtm.setRowCount(0);
        for(Airlines a : airlineDir.getAirlineDir()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=a;
           // row[1]=a.getAirlineName();
            row[1]=a.getAirlineType();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAirlinesBtn = new javax.swing.JButton();
        addFlightBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirlineDirectory = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        flightscheduleBtn = new javax.swing.JButton();

        addAirlinesBtn.setText("Add Airlines");
        addAirlinesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAirlinesBtnActionPerformed(evt);
            }
        });

        addFlightBtn.setText("Add Flights");
        addFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightBtnActionPerformed(evt);
            }
        });

        tblAirlineDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airline Name", "Type"
            }
        ));
        jScrollPane1.setViewportView(tblAirlineDirectory);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        flightscheduleBtn.setText("View Flight Schedule");
        flightscheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightscheduleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addAirlinesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(addFlightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(flightscheduleBtn)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAirlinesBtn)
                    .addComponent(addFlightBtn)
                    .addComponent(flightscheduleBtn))
                .addGap(31, 31, 31)
                .addComponent(backBtn)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAirlinesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAirlinesBtnActionPerformed
        // TODO add your handling code here:
        CreateAirlinerPanel panel = new CreateAirlinerPanel(leftpanel,airlineDir,tblAirlineDirectory);
        leftpanel.add("CreateAirlinerPanel",panel);
        CardLayout layout = (CardLayout) leftpanel.getLayout();
        layout.next(leftpanel);
    }//GEN-LAST:event_addAirlinesBtnActionPerformed

    private void addFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightBtnActionPerformed
        // TODO add your handling code here:
        SelectAirlinesPanel panel = new SelectAirlinesPanel(leftpanel,airlineDir);
        leftpanel.add("SelectAirlinesPanel",panel);
        CardLayout layout = (CardLayout) leftpanel.getLayout();
        layout.next(leftpanel);
    }//GEN-LAST:event_addFlightBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        leftpanel.remove(this);
        CardLayout layout = (CardLayout) leftpanel.getLayout();
        layout.previous(leftpanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void flightscheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightscheduleBtnActionPerformed
        // TODO add your handling code here:
        FlightSchedulePanel panel = new FlightSchedulePanel(leftpanel,airlineDir);
        leftpanel.add("FlightSchedulePanel",panel);
        CardLayout layout = (CardLayout) leftpanel.getLayout();
        layout.next(leftpanel); 
    }//GEN-LAST:event_flightscheduleBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAirlinesBtn;
    private javax.swing.JButton addFlightBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton flightscheduleBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirlineDirectory;
    // End of variables declaration//GEN-END:variables

}
